---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Import vprofile setup Variable
      include_vars: vars/vprostacksetup
  
    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into bastion-key.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: ./loginkey_vpro.pem
        mode: 0600
      when: vprokey_out.changed
    - name: Create Security group for Load Balancer
      ec2_group:
        name: vpro_ELB
        description: Allow Port 80 from everywhere and all port within sg
        region: "{{region}}"
        vpcid: "{{vpcid}}"
        rule:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out